version: '2'
services:

  server:
    image: jguillermo/angular2:server
    volumes:
      - ./../app:/usr/src/app/app
      - ./../routers:/usr/src/app/routers
    command: npm start
    ports:
      - 8084:8080